#!/bin/bash

function usage {
  cat<<EOF
Usage: ./install <install-to-path>
  See INSTALL.md for instructions.
EOF
}

function failure_and_die {
  echo "UPC++ Installation failed. Please report the entire log above to: upcxx@googlegroups.com" >&2
  exit 1
}

function echo_and_die {
  echo $* >&2
  exit 1
}

if [[ "$1" = "-h" || "$1" = "--help" ]]; then
  usage
  exit 0
elif [ "$#" -eq 1 ]; then
  single=0
  install_to="$1"
elif [ "$#" -eq 2 ]; then
  if [ "$1" != "--single" ]; then
    >&2 usage
    exit 1
  fi
  single=1
  install_to="$2"
else
  >&2 usage
  exit 1
fi

trap failure_and_die ERR

. sourceme
install_to=$(absify "$install_to")

. utils/system-checks.sh
sys_info
platform_sanity_checks
platform_settings

if [ "$single" -eq 1 ]; then
  nobs install src/upcxx.cpp "$install_to" \
    || failure_and_die
else
  # Let's not purge nobs before each install FOR DEVELOPERS to:
  #  1. Make installations after incremental updates fast.
  #  2. Encourage devs tripping on remaining bugs, so they can be reported.
  test -d .git || rm -rf .nobs
  
  case $(nobs gasnet_user_kind) in
  tarball|tarball-url|source)
    ;;
  *)
    echo_and_die "GASNET must point to local tarball file, tarball url, or gasnet source tree."
    ;;
  esac
  
  function foreach_codemode {
    export ASSERT=1 DBGSYM=1 OPTLEV=0
    export upcxx_codemode='debug'
    export gasnet_codemode='debug'
    foreach_backend
    
    if false; then
      # Attempting O2 is pointless since gasnet forces everyone to O3
      # through the CXXFLAGS it exports in makefile fragments.
      export ASSERT=0 DBGSYM=0 OPTLEV=2
      export upcxx_codemode='O2'
      export gasnet_codemode='opt'
      foreach_backend
    fi
    
    export ASSERT=0 DBGSYM=0 OPTLEV=3
    export upcxx_codemode='O3'
    export gasnet_codemode='opt'
    foreach_backend
  }
  
  function foreach_backend {
    export UPCXX_BACKEND=gasnet_seq
    foreach_conduit
    
    export UPCXX_BACKEND=gasnet_par
    foreach_conduit
  }
  
  function foreach_conduit {
    conduits=$(GASNET_CONDUIT='' nobs gasnet_configured_conduits)
    if [ $? -ne 0 ]; then failure_and_die; fi
    
    for conduit in ${conduits}; do
      export GASNET_INSTALL_TO="${install_to}/gasnet.${gasnet_codemode}"
      export GASNET_CONDUIT=${conduit}
      nobs install src/upcxx.cpp "${install_to}/upcxx.${upcxx_codemode}.${UPCXX_BACKEND}.${conduit}" \
        || failure_and_die
    done
  }
  
  foreach_codemode
  
  conduits=$(nobs gasnet_configured_conduits)
  conduits_pipes="${conduits//$'\n'/|}"
  conduits_commas="${conduits//$'\n'/, }"
  
  conduit_default=$(GASNET_CONDUIT='' nobs gasnet_conduit)
  
  mkdir -p "${install_to}/bin"
  cat <<EOF >| "${install_to}/bin/upcxx-meta"
#!/bin/bash
# This file is generated during installation - do not edit

function echo_and_die {
  echo \$* >&2
  exit 1
}

PARAMS="PPFLAGS LIBFLAGS LDFLAGS CXX CC GASNET_CONDUIT GASNET_INSTALL"
FAIL=true
for P in \$PARAMS; do
    if [[ "\$1" == "\$P" ]]; then
        FAIL=false
        break
    fi
done

if [[ \$FAIL == true ]]; then
    echo_and_die "Error: parameter passed to upcxx-meta must be one of \$PARAMS"
fi

case \${UPCXX_CODEMODE} in
"")
  UPCXX_CODEMODE=O3
  ;;
debug|O3)
  ;;
*)
  echo_and_die "UPCXX_CODEMODE must be set to one of: O3 (default), debug"
  ;;
esac

case \${UPCXX_THREADMODE} in
"")
  UPCXX_THREADMODE=seq
  ;;
seq|par)
  ;;
*)
  echo_and_die "UPCXX_THREADMODE must be set to one of: seq (default), par"
  ;;
esac

case "\${UPCXX_GASNET_CONDUIT}" in
'')
  UPCXX_GASNET_CONDUIT="${conduit_default}"
  ;;
${conduits_pipes})
  ;;
*)
  echo_and_die "UPCXX_GASNET_CONDUIT must be one of: ${conduits_commas}"
  ;;
esac

case \${UPCXX_THREADMODE} in
seq)
  UPCXX_BACKEND=gasnet_seq
  ;;
par)
  UPCXX_BACKEND=gasnet_par
  ;;
esac

${install_to}/upcxx.\${UPCXX_CODEMODE}.\${UPCXX_BACKEND}.\${UPCXX_GASNET_CONDUIT}/bin/upcxx-meta \$*
EOF
  chmod 755 "${install_to}/bin/upcxx-meta"
  cp ./utils/upcxx-run "${install_to}/bin/upcxx-run"
  chmod 755 "${install_to}/bin/upcxx-run"
  # install documentation
  docdir="${install_to}/share/doc/upcxx"
  mkdir -p $docdir
  cp -f -R README.md LICENSE.txt docs $docdir
  chmod -R a+rX $docdir
fi

echo "UPC++ successfully installed"
